### ISSUE TITLE
Client as server

### ISSUE THREAD

**Issue by hex** [theIedU/Lockstep#1]
I am curious why did you chose to make a client act as a server and not use a separate server. Is this for testing reasons only? Thanks.

Great work!

**Comment by edornd** [comment]
Sorry for the late response, busy times! Almost forgot about your answer. Well, it is indeed a testing project, more like a proof of concept than a finished "product", so that's partly the reason. 
However, the basic idea was to create a simple "hybrid" network architecture, trying to keep the good parts of the classic client-server and p2p models. In this case every client can act as host or connect to other clients hosting a game, without the need for a dedicated server and a p2p architecture (that would complicate things a bit, because of the decentralized communications).
On the other hand, the architecture still uses an authoritative model, allowing for a higher degree of control over the data sent between the players (thinking about cheating or unwanted packets, it would surely help having a server filtering), and the server code is an almost independent module, that could be easily detached from the whole project and converted into a dedicated executable.
This work is a bit of a "hobby project", the whole thing is still unfinished, and unfortunately I won't be able to actively work on it for a while, but I will almost certainly come back to it in the future, since it still has lots of flaws and stuff I'd like to change. For instance, the whole simulation module is currently organized to work on its own thread, but after some testing it seemed a bit overkill and almost unnecessary, so I'll probably switch back to the main unity thread, if I don't find any good reason to keep it separate.

Anyway, sorry for the wall of text, I hope I answered your question, more or less.
If you have any doubts or suggestions feel free to ask/comment! I'll try to answer a bit faster next time :)
Cheers!
